SELECT U.USER_ID,U.NICKNAME, SUM(B.PRICE) AS PRICE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID
HAVING PRICE>=700000
ORDER BY PRICE ASC;