SELECT i2.ITEM_ID, i2.ITEM_NAME, i2.RARITY
FROM ITEM_INFO i1
JOIN ITEM_TREE t ON i1.ITEM_ID = t.PARENT_ITEM_ID
JOIN ITEM_INFO i2 ON t.ITEM_ID = i2.ITEM_ID
WHERE i1.RARITY = 'RARE'
ORDER BY i2.ITEM_ID DESC;
